version: "3.9"

services:
  # === DB locale (active-la seulement si tu veux bosser sans DB partagée) ===
  db:
    image: postgres:16
    container_name: lockfit_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: lockfit
      POSTGRES_USER: lockfit
      POSTGRES_PASSWORD: lockfit
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    profiles: ["local-db"]

  # (Optionnel) UI web pour la DB locale
  pgadmin:
    image: dpage/pgadmin4:8
    container_name: lockfit_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.test
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    profiles: ["local-db"]

  # === Backend NestJS (dev) ===
  backend:
    image: node:20
    container_name: lockfit_backend
    working_dir: /app
    volumes:
      - ./Backend:/app
      - /app/node_modules
    env_file:
      - ./Backend/.env
    environment:
      PORT: "3001"
      CHOKIDAR_USEPOLLING: "true"   # watch fiable dans un conteneur
    command: >
      sh -lc "npm ci || npm i
      && npx prisma generate || true
      && npm run start:dev"
    ports:
      - "3001:3001"
    # ⚠️ Pas de depends_on:db ici pour rester compatible avec une DB partagée (Neon/Supabase)

volumes:
  pgdata:
